/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OgImageRouteImport } from './routes/og-image'
import { Route as Char123LocaleChar125RouteRouteImport } from './routes/{-$locale}/route'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125AboutRouteImport } from './routes/{-$locale}/about'
import { Route as Char123LocaleChar125ContactRouteImport } from './routes/{-$locale}/contact'
import { Route as Char123LocaleChar125MediaRouteImport } from './routes/{-$locale}/media'
import { Route as Char123LocaleChar125ProjectsRouteImport } from './routes/{-$locale}/projects'
import { Route as Char123LocaleChar125ServicesRouteImport } from './routes/{-$locale}/services'
import { Route as Char123LocaleChar125MediaIndexRouteImport } from './routes/{-$locale}/media.index'
import { Route as Char123LocaleChar125MediaArticleIdRouteImport } from './routes/{-$locale}/media.$articleId'
import { Route as Char123LocaleChar125ProjectsIndexRouteImport } from './routes/{-$locale}/projects.index'
import { Route as Char123LocaleChar125ProjectsProjectIdRouteImport } from './routes/{-$locale}/projects.$projectId'
import { Route as Char123LocaleChar125ProjectsProjectIdIndexRouteImport } from './routes/{-$locale}/projects.$projectId.index'
import { Route as Char123LocaleChar125ProjectsProjectIdProgressRouteImport } from './routes/{-$locale}/projects.$projectId.progress'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OgImageRoute = OgImageRouteImport.update({
  id: '/og-image',
  path: '/og-image',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125RouteRoute =
  Char123LocaleChar125RouteRouteImport.update({
    id: '/{-$locale}',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AboutRoute =
  Char123LocaleChar125AboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ContactRoute =
  Char123LocaleChar125ContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125MediaRoute =
  Char123LocaleChar125MediaRouteImport.update({
    id: '/media',
    path: '/media',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ProjectsRoute =
  Char123LocaleChar125ProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ServicesRoute =
  Char123LocaleChar125ServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125MediaIndexRoute =
  Char123LocaleChar125MediaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125MediaRoute,
  } as any)
const Char123LocaleChar125MediaArticleIdRoute =
  Char123LocaleChar125MediaArticleIdRouteImport.update({
    id: '/$articleId',
    path: '/$articleId',
    getParentRoute: () => Char123LocaleChar125MediaRoute,
  } as any)
const Char123LocaleChar125ProjectsIndexRoute =
  Char123LocaleChar125ProjectsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125ProjectsRoute,
  } as any)
const Char123LocaleChar125ProjectsProjectIdRoute =
  Char123LocaleChar125ProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => Char123LocaleChar125ProjectsRoute,
  } as any)
const Char123LocaleChar125ProjectsProjectIdIndexRoute =
  Char123LocaleChar125ProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125ProjectsProjectIdRoute,
  } as any)
const Char123LocaleChar125ProjectsProjectIdProgressRoute =
  Char123LocaleChar125ProjectsProjectIdProgressRouteImport.update({
    id: '/progress',
    path: '/progress',
    getParentRoute: () => Char123LocaleChar125ProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/og-image': typeof OgImageRoute
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/media': typeof Char123LocaleChar125MediaRouteWithChildren
  '/{-$locale}/projects': typeof Char123LocaleChar125ProjectsRouteWithChildren
  '/{-$locale}/services': typeof Char123LocaleChar125ServicesRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/media/$articleId': typeof Char123LocaleChar125MediaArticleIdRoute
  '/{-$locale}/projects/$projectId': typeof Char123LocaleChar125ProjectsProjectIdRouteWithChildren
  '/{-$locale}/media/': typeof Char123LocaleChar125MediaIndexRoute
  '/{-$locale}/projects/': typeof Char123LocaleChar125ProjectsIndexRoute
  '/{-$locale}/projects/$projectId/progress': typeof Char123LocaleChar125ProjectsProjectIdProgressRoute
  '/{-$locale}/projects/$projectId/': typeof Char123LocaleChar125ProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/og-image': typeof OgImageRoute
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/services': typeof Char123LocaleChar125ServicesRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/media/$articleId': typeof Char123LocaleChar125MediaArticleIdRoute
  '/{-$locale}/media': typeof Char123LocaleChar125MediaIndexRoute
  '/{-$locale}/projects': typeof Char123LocaleChar125ProjectsIndexRoute
  '/{-$locale}/projects/$projectId/progress': typeof Char123LocaleChar125ProjectsProjectIdProgressRoute
  '/{-$locale}/projects/$projectId': typeof Char123LocaleChar125ProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/og-image': typeof OgImageRoute
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/media': typeof Char123LocaleChar125MediaRouteWithChildren
  '/{-$locale}/projects': typeof Char123LocaleChar125ProjectsRouteWithChildren
  '/{-$locale}/services': typeof Char123LocaleChar125ServicesRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/media/$articleId': typeof Char123LocaleChar125MediaArticleIdRoute
  '/{-$locale}/projects/$projectId': typeof Char123LocaleChar125ProjectsProjectIdRouteWithChildren
  '/{-$locale}/media/': typeof Char123LocaleChar125MediaIndexRoute
  '/{-$locale}/projects/': typeof Char123LocaleChar125ProjectsIndexRoute
  '/{-$locale}/projects/$projectId/progress': typeof Char123LocaleChar125ProjectsProjectIdProgressRoute
  '/{-$locale}/projects/$projectId/': typeof Char123LocaleChar125ProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/{-$locale}'
    | '/og-image'
    | '/{-$locale}/about'
    | '/{-$locale}/contact'
    | '/{-$locale}/media'
    | '/{-$locale}/projects'
    | '/{-$locale}/services'
    | '/{-$locale}/'
    | '/{-$locale}/media/$articleId'
    | '/{-$locale}/projects/$projectId'
    | '/{-$locale}/media/'
    | '/{-$locale}/projects/'
    | '/{-$locale}/projects/$projectId/progress'
    | '/{-$locale}/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/og-image'
    | '/{-$locale}/about'
    | '/{-$locale}/contact'
    | '/{-$locale}/services'
    | '/{-$locale}'
    | '/{-$locale}/media/$articleId'
    | '/{-$locale}/media'
    | '/{-$locale}/projects'
    | '/{-$locale}/projects/$projectId/progress'
    | '/{-$locale}/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/{-$locale}'
    | '/og-image'
    | '/{-$locale}/about'
    | '/{-$locale}/contact'
    | '/{-$locale}/media'
    | '/{-$locale}/projects'
    | '/{-$locale}/services'
    | '/{-$locale}/'
    | '/{-$locale}/media/$articleId'
    | '/{-$locale}/projects/$projectId'
    | '/{-$locale}/media/'
    | '/{-$locale}/projects/'
    | '/{-$locale}/projects/$projectId/progress'
    | '/{-$locale}/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Char123LocaleChar125RouteRoute: typeof Char123LocaleChar125RouteRouteWithChildren
  OgImageRoute: typeof OgImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og-image': {
      id: '/og-image'
      path: '/og-image'
      fullPath: '/og-image'
      preLoaderRoute: typeof OgImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/about': {
      id: '/{-$locale}/about'
      path: '/about'
      fullPath: '/{-$locale}/about'
      preLoaderRoute: typeof Char123LocaleChar125AboutRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/contact': {
      id: '/{-$locale}/contact'
      path: '/contact'
      fullPath: '/{-$locale}/contact'
      preLoaderRoute: typeof Char123LocaleChar125ContactRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/media': {
      id: '/{-$locale}/media'
      path: '/media'
      fullPath: '/{-$locale}/media'
      preLoaderRoute: typeof Char123LocaleChar125MediaRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/projects': {
      id: '/{-$locale}/projects'
      path: '/projects'
      fullPath: '/{-$locale}/projects'
      preLoaderRoute: typeof Char123LocaleChar125ProjectsRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/services': {
      id: '/{-$locale}/services'
      path: '/services'
      fullPath: '/{-$locale}/services'
      preLoaderRoute: typeof Char123LocaleChar125ServicesRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/media/': {
      id: '/{-$locale}/media/'
      path: '/'
      fullPath: '/{-$locale}/media/'
      preLoaderRoute: typeof Char123LocaleChar125MediaIndexRouteImport
      parentRoute: typeof Char123LocaleChar125MediaRoute
    }
    '/{-$locale}/media/$articleId': {
      id: '/{-$locale}/media/$articleId'
      path: '/$articleId'
      fullPath: '/{-$locale}/media/$articleId'
      preLoaderRoute: typeof Char123LocaleChar125MediaArticleIdRouteImport
      parentRoute: typeof Char123LocaleChar125MediaRoute
    }
    '/{-$locale}/projects/': {
      id: '/{-$locale}/projects/'
      path: '/'
      fullPath: '/{-$locale}/projects/'
      preLoaderRoute: typeof Char123LocaleChar125ProjectsIndexRouteImport
      parentRoute: typeof Char123LocaleChar125ProjectsRoute
    }
    '/{-$locale}/projects/$projectId': {
      id: '/{-$locale}/projects/$projectId'
      path: '/$projectId'
      fullPath: '/{-$locale}/projects/$projectId'
      preLoaderRoute: typeof Char123LocaleChar125ProjectsProjectIdRouteImport
      parentRoute: typeof Char123LocaleChar125ProjectsRoute
    }
    '/{-$locale}/projects/$projectId/': {
      id: '/{-$locale}/projects/$projectId/'
      path: '/'
      fullPath: '/{-$locale}/projects/$projectId/'
      preLoaderRoute: typeof Char123LocaleChar125ProjectsProjectIdIndexRouteImport
      parentRoute: typeof Char123LocaleChar125ProjectsProjectIdRoute
    }
    '/{-$locale}/projects/$projectId/progress': {
      id: '/{-$locale}/projects/$projectId/progress'
      path: '/progress'
      fullPath: '/{-$locale}/projects/$projectId/progress'
      preLoaderRoute: typeof Char123LocaleChar125ProjectsProjectIdProgressRouteImport
      parentRoute: typeof Char123LocaleChar125ProjectsProjectIdRoute
    }
  }
}

interface Char123LocaleChar125MediaRouteChildren {
  Char123LocaleChar125MediaArticleIdRoute: typeof Char123LocaleChar125MediaArticleIdRoute
  Char123LocaleChar125MediaIndexRoute: typeof Char123LocaleChar125MediaIndexRoute
}

const Char123LocaleChar125MediaRouteChildren: Char123LocaleChar125MediaRouteChildren =
  {
    Char123LocaleChar125MediaArticleIdRoute:
      Char123LocaleChar125MediaArticleIdRoute,
    Char123LocaleChar125MediaIndexRoute: Char123LocaleChar125MediaIndexRoute,
  }

const Char123LocaleChar125MediaRouteWithChildren =
  Char123LocaleChar125MediaRoute._addFileChildren(
    Char123LocaleChar125MediaRouteChildren,
  )

interface Char123LocaleChar125ProjectsProjectIdRouteChildren {
  Char123LocaleChar125ProjectsProjectIdProgressRoute: typeof Char123LocaleChar125ProjectsProjectIdProgressRoute
  Char123LocaleChar125ProjectsProjectIdIndexRoute: typeof Char123LocaleChar125ProjectsProjectIdIndexRoute
}

const Char123LocaleChar125ProjectsProjectIdRouteChildren: Char123LocaleChar125ProjectsProjectIdRouteChildren =
  {
    Char123LocaleChar125ProjectsProjectIdProgressRoute:
      Char123LocaleChar125ProjectsProjectIdProgressRoute,
    Char123LocaleChar125ProjectsProjectIdIndexRoute:
      Char123LocaleChar125ProjectsProjectIdIndexRoute,
  }

const Char123LocaleChar125ProjectsProjectIdRouteWithChildren =
  Char123LocaleChar125ProjectsProjectIdRoute._addFileChildren(
    Char123LocaleChar125ProjectsProjectIdRouteChildren,
  )

interface Char123LocaleChar125ProjectsRouteChildren {
  Char123LocaleChar125ProjectsProjectIdRoute: typeof Char123LocaleChar125ProjectsProjectIdRouteWithChildren
  Char123LocaleChar125ProjectsIndexRoute: typeof Char123LocaleChar125ProjectsIndexRoute
}

const Char123LocaleChar125ProjectsRouteChildren: Char123LocaleChar125ProjectsRouteChildren =
  {
    Char123LocaleChar125ProjectsProjectIdRoute:
      Char123LocaleChar125ProjectsProjectIdRouteWithChildren,
    Char123LocaleChar125ProjectsIndexRoute:
      Char123LocaleChar125ProjectsIndexRoute,
  }

const Char123LocaleChar125ProjectsRouteWithChildren =
  Char123LocaleChar125ProjectsRoute._addFileChildren(
    Char123LocaleChar125ProjectsRouteChildren,
  )

interface Char123LocaleChar125RouteRouteChildren {
  Char123LocaleChar125AboutRoute: typeof Char123LocaleChar125AboutRoute
  Char123LocaleChar125ContactRoute: typeof Char123LocaleChar125ContactRoute
  Char123LocaleChar125MediaRoute: typeof Char123LocaleChar125MediaRouteWithChildren
  Char123LocaleChar125ProjectsRoute: typeof Char123LocaleChar125ProjectsRouteWithChildren
  Char123LocaleChar125ServicesRoute: typeof Char123LocaleChar125ServicesRoute
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
}

const Char123LocaleChar125RouteRouteChildren: Char123LocaleChar125RouteRouteChildren =
  {
    Char123LocaleChar125AboutRoute: Char123LocaleChar125AboutRoute,
    Char123LocaleChar125ContactRoute: Char123LocaleChar125ContactRoute,
    Char123LocaleChar125MediaRoute: Char123LocaleChar125MediaRouteWithChildren,
    Char123LocaleChar125ProjectsRoute:
      Char123LocaleChar125ProjectsRouteWithChildren,
    Char123LocaleChar125ServicesRoute: Char123LocaleChar125ServicesRoute,
    Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
  }

const Char123LocaleChar125RouteRouteWithChildren =
  Char123LocaleChar125RouteRoute._addFileChildren(
    Char123LocaleChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Char123LocaleChar125RouteRoute: Char123LocaleChar125RouteRouteWithChildren,
  OgImageRoute: OgImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
